db.url=${DB_URL}
db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}
db.driver=org.postgresql.Driver

db.pool.maximum-pool-size=5
db.pool.minimum-idle=1
db.pool.connection-timeout-ms=10000
db.pool.idle-timeout-ms=600000
db.pool.max-lifetime-ms=1800000